expose test helper run in library
gcanti/parser-ts pull request #34
Opened 2020-08-31 10:03 UTC by waynevanson

Did not export as a main module, as it's not really a module by fp-ts standards.

Instead, it can be access by `import { run } from "parser-ts/lib/helpers"`

closes #33

2020-08-31 12:39 UTC, gcanti commented
> it can be access by import { run } from "parser-ts/lib/helpers"

what about moving `run` to the `Parser` module instead?

2020-08-31 12:53 UTC, IMax153 commented
We could also consider moving the `run` helper to the `string` module, since the `Parser` that is being "run" is *technically* a string parser

```typescript
type StringParser<A> = Parser<Char, A>
````

2020-09-21 13:15 UTC, IMax153 requested changes

2020-09-21 13:15 UTC, IMax153 commented on package-lock.json
> +  "version": "0.6.8",
You can leave the `parser-ts` version number as is - it will be updated on release, so no need to bump here.

2020-09-21 13:15 UTC, IMax153 commented on src/helpers.ts
> +export function run<A>(p: Parser<Char, A>, s: string): ParseResult<Char, A> {
I think based on the discussion above, we should move this helper into the `string` module.

2020-09-27 00:07 UTC, IMax153 commented
@gcanti - Are you okay with the `run` helper in the `char` module? I am indifferent. I think it makes sense in either the `string` or the `char` module.

Otherwise this PR LGTM 👍.

2020-09-27 01:19 UTC, waynevanson commented
Know I think about it, it should be in the string module right? Because a string is the first parameter,  not char

2020-09-28 12:27 UTC, IMax153 commented
@waynevanson - personally, I do think it makes more sense to include the `run` helper in the `string` module as opposed to the `char` module since the actual entity being parsed (and consequently what is passed to the `run` helper) is a string (even though the `Stream` is an array of characters).

2020-09-29 08:41 UTC, waynevanson commented
In it goes. I'll ping when it's ready.

2021-02-24 22:15 UTC, IMax153 commented
Hey @waynevanson! Just wanted to check in on the status of this PR - are we still good to move the `run` helper to the `string` module? Thanks!

2021-03-19 13:48 UTC, waynevanson commented
@IMax153 Sorry about the ridiculous delay. I've gone the extra mile to remove conflicts by doing a manual rebase :)

2021-03-20 14:15 UTC, IMax153 approved these changes
LGTM!

2021-03-20 14:15 UTC, merged

2021-03-20 14:16 UTC, IMax153 commented
@gcanti, @waynevanson - Merged!

Thanks @waynevanson! 👍

2021-03-23 07:34 UTC, gcanti commented
Thanks, released.