feat(char): isLetter: handle all Latin scripts
gcanti/parser-ts pull request #52
Opened 2021-11-01 16:42 UTC by frysztak

makes `isLetter` handle -- as far as I know -- all Latin scripts, rather than just `a-z` range

2021-11-02 22:15 UTC, IMax153 requested changes
I'm okay with this change, although semantically if I were reaching for the `isLetter` combinator I would be thinking of characters in the `[a-zA-Z]` range. That's probably just me though 🤣 .

I would like to have a few more test cases added though to prove that this logic indeed holds up.

2021-11-04 07:34 UTC, frysztak commented
@IMax153 would you be more comfortable if I added another combinator? say, `isUnicodeLetter`?

2021-11-04 12:23 UTC, IMax153 commented
@frysztak - yea I think that's a better way to go for now. Let's just add the additional combinator 👍

2021-11-07 21:41 UTC, frysztak commented
@IMax153 done!

2021-11-08 21:37 UTC, IMax153 approved these changes

2021-11-08 21:38 UTC, merged

2021-11-08 21:38 UTC, IMax153 commented
LGTM! Thanks @frysztak! @gcanti - merging this PR 👍

2021-11-10 08:50 UTC, gcanti commented
Thank you all, released